/* =====================================================================
   Brothers Interactive — SITE CONTENT
   Edit this file to update the site. No code knowledge needed:
   keep the quotes and commas, save, refresh.
   ===================================================================== */

window.BI = {

  /* ---- Settings (fill in when you have the accounts) ---- */
  CONFIG: {
    availability: "Taking new projects",            // header pill text; "" hides it
    availabilityNote: "Next start: on request",     // small line under the pill
    formspreeId: "",                                // e.g. "xyzabcde" from formspree.io — empty = email client fallback
    bookingUrl: "",                                 // e.g. "https://calendly.com/brothersinteractive/intro" — empty hides the button
    plausibleDomain: "",                            // e.g. "brothersinteractive.com" — empty = analytics off
    showreelYouTubeId: "",                          // e.g. "dQw4w9WgXcQ" — empty = image reel from the portfolio
    deckPdf: "assets/brothers-interactive-capabilities.pdf",
    email: "business@brothersinteractive.com",
    address: "79/5 Shipra Path, Mansarovar, Jaipur 302017, Rajasthan, India"
  },

  /* ---- Quote estimator: typical artist-days per asset (ranges), editable ---- */
  ESTIMATOR: {
    types: {
      "Hero character": { realistic: [18, 30], stylized: [12, 22], handpainted: [10, 18] },
      "NPC / secondary character": { realistic: [10, 18], stylized: [7, 14], handpainted: [6, 12] },
      "Creature": { realistic: [14, 26], stylized: [10, 18], handpainted: [8, 15] },
      "Hero prop / weapon": { realistic: [4, 8], stylized: [3, 6], handpainted: [3, 5] },
      "Simple prop": { realistic: [1, 3], stylized: [1, 2], handpainted: [1, 2] },
      "Hair set": { realistic: [4, 8], stylized: [2, 5], handpainted: [2, 4] }
    },
    rigging: [3, 6],       // extra days per character when rigging is needed
    outfitVariant: [3, 6], // extra days per variant
    parallelArtists: 4     // how many artists typically work in parallel on one project
  },

  /* ---- Client logo wall (text wordmarks; add {logo:"assets/img/logos/x.webp"} when you have permission) ---- */
  CLIENTS: [
    { n: "Saber Interactive" }, { n: "Thunderful" }, { n: "Midwinter Entertainment" }, { n: "Slipgate Ironworks" },
    { n: "MoonHood Studios" }, { n: "VOID Interactive" }, { n: "Zoink Games" }, { n: "Event Horizon" }
  ],

  /* ---- Testimonials: { q: "quote", n: "Name", r: "Art Director, Studio", img: "assets/img/team/x.webp" }
     The three entries below are SAMPLES (sample: true shows a badge). Replace them with real, approved quotes. ---- */
  TESTIMONIALS: [
    { sample: true, q: "The characters matched our in-house style so closely that our own team could not tell which ones were outsourced.", n: "Client name", r: "Art Director, AAA studio", project: "Realistic characters" },
    { sample: true, q: "Clear weekly updates, zero surprises on the deadline, and every revision note handled the same day.", n: "Client name", r: "Producer, indie studio", project: "Stylized cast" },
    { sample: true, q: "Sculpt quality was the best we have seen from an outsourcing partner. We brought them back for the next title.", n: "Client name", r: "Lead Character Artist", project: "Creatures & props" }
  ],

  /* ---- Open roles: { t: "Senior Character Artist", type: "Full-time · Jaipur", d: "One-line summary" } ---- */
  ROLES: [],

  /* ---- Press & recognition: { t: "Title", src: "Publication", url: "https://...", d: "Mar 2025" } ---- */
  PRESS: [],

  /* ---- Sculpt-to-final comparison pairs (auto-detected from the portfolio) ---- */
  PAIRS: [
      {
          "id": "xdAzDY",
          "t": "Cute Monster",
          "before": "assets/img/portfolio/cute-monster-xdazdy-before.webp",
          "after": "assets/img/portfolio/cute-monster-xdazdy-after.webp"
      },
      {
          "id": "vbNvDE",
          "t": "Orc Fanart",
          "before": "assets/img/portfolio/orc-fanart-vbnvde-before.webp",
          "after": "assets/img/portfolio/orc-fanart-vbnvde-after.webp"
      },
      {
          "id": "mAnNrv",
          "t": "T-Rex - Crash Bandicoot 4 Fanart",
          "before": "assets/img/portfolio/t-rex-crash-bandicoot-4-fanart-mannrv-before.webp",
          "after": "assets/img/portfolio/t-rex-crash-bandicoot-4-fanart-mannrv-after.webp"
      },
      {
          "id": "rJVn4e",
          "t": "Zombie-2",
          "before": "assets/img/portfolio/zombie-2-rjvn4e-before.webp",
          "after": "assets/img/portfolio/zombie-2-rjvn4e-after.webp"
      },
      {
          "id": "qJY3qa",
          "t": "Orc",
          "before": "assets/img/portfolio/orc-qjy3qa-before.webp",
          "after": "assets/img/portfolio/orc-qjy3qa-after.webp"
      },
      {
          "id": "dKWXLA",
          "t": "Lehri",
          "before": "assets/img/portfolio/lehri-dkwxla-before.webp",
          "after": "assets/img/portfolio/lehri-dkwxla-after.webp"
      }
  ],

  /* ---- Case studies (cat pulls thumbnails from PROJECTS; stats rows are optional) ---- */
  CASES: [
    {
      t: "Lost in Random", client: "Zoink Games / Thunderful", year: "2021", style: "Stylized", engine: "Unity",
      img: "assets/img/games/lost-in-random.webp", yt: "diilMn5gSAg", cat: "lost-in-random", stats: [["Published assets", "11"], ["Style", "Stylized"], ["Team size", "Add"], ["Timeline", "Add"]],
      summary: "Gothic fairy-tale characters for Zoink's action adventure. We produced a cast of NPCs and enemies in the game's hand-crafted, stop-motion inspired look, from sculpt through final textures, matched to the in-house cast so the additions are indistinguishable from the studio's own work.",
      scope: ["Stylized character modeling and sculpting", "Hand-painted PBR texturing", "Game-res topology and UVs", "Style matching to existing characters"]
    },
    {
      t: "The Midnight Walk", client: "MoonHood Studios", year: "2025", style: "Stylized claymation", engine: "Unreal Engine",
      img: "assets/img/games/the-midnight-walk.webp", yt: "QnBE7mU6ZsI", cat: "mid-night-walk", stats: [["Published assets", "9"], ["Style", "Claymation"], ["Team size", "Add"], ["Timeline", "Add"]],
      summary: "Clay-sculpted characters for MoonHood's dark fairy-tale adventure. Our work covered story characters and creatures translated from physical clay reference into game-ready assets that keep the fingerprints-and-tool-marks feel of the original sculpts.",
      scope: ["Character and creature sculpting from clay reference", "Retopology and UVs for a stylized pipeline", "Texturing with hand-made surface detail", "Engine-ready exports"]
    },
    {
      t: "Warhammer 40,000: Space Marine 2", client: "Saber Interactive", year: "2024", style: "Realistic AAA", engine: "Swarm Engine",
      img: "assets/img/games/warhammer-40-000-space-marine-2.webp", yt: "A_HljUo8Jjk", cat: null,
      summary: "Character and asset production support on Saber Interactive's AAA action title. Details of individual assets are shared on request in line with the project's confidentiality terms.",
      scope: ["3D modeling and sculpting", "Texturing", "Skinning and rigging", "Engine integration support"]
    },
    {
      t: "Ready Or Not", client: "VOID Interactive", year: "2023", style: "Realistic", engine: "Unreal Engine",
      img: "assets/img/games/ready-or-not.webp", yt: "lLNoftAmKr0", cat: null,
      summary: "Realistic character and equipment production support for VOID Interactive's tactical shooter. Asset breakdowns are available on request.",
      scope: ["Realistic character modeling", "Gear, equipment and prop texturing", "Skinning and rigging support", "Optimization for Unreal"]
    },
    {
      t: "Wavetale", client: "Thunderful Development", year: "2022", style: "Stylized", engine: "Unity",
      img: "assets/img/games/wavetale.webp", yt: "Zeths3LNBgQ", cat: null,
      summary: "Stylized character work for Thunderful's ocean-surfing adventure. Asset breakdowns are available on request.",
      scope: ["Stylized character modeling", "Texturing", "Game-res topology and UVs"]
    }
  ],

  /* ---- Blog posts (titles + dates from the live blog) ---- */
  POSTS: [
    { t: "Marathon 2025", d: "04 Feb 2025" },
    { t: "Christmas Celebration 2024", d: "24 Jan 2025" },
    { t: "Christmas 2023 Highlights", d: "12 Jan 2024" },
    { t: "Casino Night in Goa: Brothers' Style", d: "04 Jan 2024" },
    { t: "Soothing Goa Retreat", d: "04 Jan 2024" },
    { t: "Goa Getaway Diaries", d: "04 Jan 2024" }
  ],

  /* ---- Game credits ---- */
  GAMES: [
    {"t": "Tormentor", "s": "Slipgate Ironworks", "yt": "FRMIpc-JiOM", "i": "assets/img/games/tormentor.webp"},
    {"t": "The Midnight Walk", "s": "MoonHood Studios", "yt": "QnBE7mU6ZsI", "i": "assets/img/games/the-midnight-walk.webp"},
    {"t": "Warhammer 40,000: Space Marine 2", "s": "Saber Interactive", "yt": "A_HljUo8Jjk", "i": "assets/img/games/warhammer-40-000-space-marine-2.webp"},
    {"t": "Ready or Not", "s": "VOID Interactive", "yt": "lLNoftAmKr0", "i": "assets/img/games/ready-or-not.webp"},
    {"t": "Supermoves", "s": "Makea Games", "yt": "TetKQGIBjvo", "i": "assets/img/games/supermoves.webp"},
    {"t": "Warhammer 40,000: Speed Freeks", "s": "Caliber Games", "yt": "tqSelvOZnHU", "i": "assets/img/games/warhammer-40-000-speed-freeks.webp"},
    {"t": "Dark Envoy", "s": "Event Horizon", "yt": "I07Gm2dpiLs", "i": "assets/img/games/dark-envoy.webp"},
    {"t": "Lost in Random", "s": "Zoink / Thunderful", "yt": "diilMn5gSAg", "i": "assets/img/games/lost-in-random.webp"},
    {"t": "The Gunk", "s": "Image & Form / Thunderful", "yt": "Cs96h12uHiE", "i": "assets/img/games/the-gunk.webp"},
    {"t": "Wavetale", "s": "Thunderful Development", "yt": "Zeths3LNBgQ", "i": "assets/img/games/wavetale.webp"},
    {"t": "Scavengers", "s": "Midwinter Entertainment", "yt": "hvq9Ov6gXc4", "i": "assets/img/games/scavengers.webp"}
  ],

  /* ---- Portfolio: t=title c=category i=main image imgs=extra images desc=description src=original page ---- */
  PROJECTS: [
    {"t": "The Adventures", "c": "stylized-human", "id": "mOZqAe", "i": "assets/img/portfolio/the-adventures-mozqae.webp", "imgs": ["assets/img/portfolio/the-adventures-mozqae-2.webp", "assets/img/portfolio/the-adventures-mozqae-3.webp", "assets/img/portfolio/the-adventures-mozqae-4.webp"], "desc": "The Adventures \nStylized 3D Character created by our team Brothers Interactive.\nWith this character, we are exploring, testing and pushing high-end stylized- clean art style, and game-ready appeal..", "tags": [], "src": "https://brothersinteractive.com/projects/mOZqAe", "w": 1000, "h": 750},
    {"t": "Monster Lizard", "c": "realistic-creatures", "id": "JwalrD", "i": "assets/img/portfolio/monster-lizard-jwalrd.webp", "imgs": ["assets/img/portfolio/monster-lizard-jwalrd-2.webp", "assets/img/portfolio/monster-lizard-jwalrd-3.webp", "assets/img/portfolio/monster-lizard-jwalrd-4.webp"], "desc": "Monster Lizard \nRealistic Enemy Character, created by our team Brothers Interactive.\nWith, we are exploring, testing and pushing  Realistic AA and AAA games art style, and game-ready appeal..", "tags": [], "src": "https://brothersinteractive.com/projects/JwalrD", "w": 1000, "h": 563},
    {"t": "Cute Monster", "c": "stylized-creature", "id": "xdAzDY", "i": "assets/img/portfolio/cute-monster-xdazdy.webp", "imgs": ["assets/img/portfolio/cute-monster-xdazdy-2.webp", "assets/img/portfolio/cute-monster-xdazdy-3.webp", "assets/img/portfolio/cute-monster-xdazdy-4.webp"], "desc": "Cute Monster,\nDeveloped internally at Brothers Interactive, \"Cute Monster\" represents our team's expertise in high-quality stylized creature and character art. This production-ready asset was built from the ground up to showcase Clean hand-painted art style approach, readability, expressive anatomical proportions, and vibrant material definition required for modern stylized fantasy and strategy titles.\n\nTechnical Breakdown:\n- Level 1 Triangle Budget: 7,090 Tris\n- Level 2 Triangle Budget: 7,582 Tris\n- Level 3 Triangle Budget: 9,548 Tris\n- Level 4 Triangle Budget: 12,548 Tris\n\n- Texturing: single 1K Diffuse map (For Each Level)\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology, ready for seamless integration into modern low-spec and cross-platform game-play engines.", "tags": [], "src": "https://brothersinteractive.com/projects/xdAzDY", "w": 1000, "h": 924},
    {"t": "Nitro CR7", "c": "stylized-human", "id": "ndwQ0O", "i": "assets/img/portfolio/nitro-cr7-ndwq0o.webp", "imgs": ["assets/img/portfolio/nitro-cr7-ndwq0o-2.webp", "assets/img/portfolio/nitro-cr7-ndwq0o-3.webp", "assets/img/portfolio/nitro-cr7-ndwq0o-4.webp"], "desc": "Nitro CR7 - WIP\nStylized 3D Character created by our team Brothers Interactive.\nWith this character, we are exploring, testing and pushing mobile games and similar art style, and game-ready appeal..\n\nNitro CR7,\nDeveloped internally at Brothers Interactive, \"Nitro CR7\" represents our team's expertise in high-quality character art. This production-ready asset was built from the ground up to showcase bold silhouette, readability, expressive anatomical proportions, and vibrant material definition required for modern stylized fantasy and strategy titles.\n\nTechnical Breakdown:\n- Budget: 12,028 Tris\n- Texturing: PBR workflow, single 2K texture set\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology, ready for seamless integration into modern low-spec and cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/ndwQ0O", "w": 1000, "h": 750},
    {"t": "Mion", "c": "stylized-human", "id": "vzA1JO", "i": "assets/img/portfolio/mion-vza1jo.webp", "imgs": ["assets/img/portfolio/mion-vza1jo-2.webp", "assets/img/portfolio/mion-vza1jo-3.webp", "assets/img/portfolio/mion-vza1jo-4.webp"], "desc": "Mion,\n\nDeveloped internally at Brothers Interactive, \"Mion\" represents our team's expertise in high-quality stylized creature and character art. This production-ready asset was built from the ground up to showcase bold Cell Shading silhouette readability, expressive anatomical proportions, and vibrant material definition required for modern stylized fantasy and strategy titles.\n\nTechnical Breakdown:\n- Budget: 20,000 Tris\n- Texturing: PBR workflow, single 2K texture set\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology, ready for seamless integration into modern low-spec and cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/vzA1JO", "w": 1000, "h": 833},
    {"t": "Orc Fanart", "c": "stylized-creature", "id": "vbNvDE", "i": "assets/img/portfolio/orc-fanart-vbnvde.webp", "imgs": ["assets/img/portfolio/orc-fanart-vbnvde-2.webp", "assets/img/portfolio/orc-fanart-vbnvde-3.webp", "assets/img/portfolio/orc-fanart-vbnvde-4.webp"], "desc": "Stylized creature sculpt created by our team Brothers Interactive.\nexploring, testing and pushing shape language, facial storytelling, and game-ready appeal. \nInspired by Wenmo Zhang's artwork.", "tags": [], "src": "https://brothersinteractive.com/projects/vbNvDE", "w": 1000, "h": 1000},
    {"t": "Lee Body", "c": "realistic-humans", "id": "yDeg2x", "i": "assets/img/portfolio/lee-body-ydeg2x.webp", "imgs": ["assets/img/portfolio/lee-body-ydeg2x-2.webp", "assets/img/portfolio/lee-body-ydeg2x-3.webp", "assets/img/portfolio/lee-body-ydeg2x-4.webp"], "desc": "AAA Real-Time Character Study: \"Lee\"\nDeveloped internally at Brothers Interactive, \"Lee\" represents our team's latest push into current-gen character art quality. This production-ready asset was built from the ground up to demonstrate high-end visual fidelity optimized for AAA platforms like PS5, Xbox Series X, and PC.\n\nTechnical Breakdown:\n- Budget: 160K Tris\n- Texturing:PBR workflow Five 4K and Four 2K sets\n- Pipeline: Ready for integration into modern AAA cinematic and gameplay pipelines.\n- Target Platforms - AAA platforms like PS5, Xbox Series X, and PC.", "tags": [], "src": "https://brothersinteractive.com/projects/yDeg2x", "w": 1000, "h": 833},
    {"t": "Red House", "c": "mid-night-walk", "id": "XaBYJ0", "i": "assets/img/portfolio/red-house-xabyj0.webp", "imgs": [], "desc": "The Midnight Walk- Red House\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/XaBYJ0", "w": 1000, "h": 672},
    {"t": "T-Rex - Crash Bandicoot 4 Fanart", "c": "stylized-creature", "id": "mAnNrv", "i": "assets/img/portfolio/t-rex-crash-bandicoot-4-fanart-mannrv.webp", "imgs": ["assets/img/portfolio/t-rex-crash-bandicoot-4-fanart-mannrv-2.webp", "assets/img/portfolio/t-rex-crash-bandicoot-4-fanart-mannrv-3.webp", "assets/img/portfolio/t-rex-crash-bandicoot-4-fanart-mannrv-4.webp"], "desc": "Stylized Character Study: \"T-Rex\" (Crash Bandicoot 4 Fan Art)\nDeveloped internally at Brothers Interactive, this asset represents our team's capability in high-quality stylized character art. Built from the ground up as a tribute to the distinct aesthetic of Crash Bandicoot 4, this production-ready asset demonstrates high-end visual appeal while maintaining an ultra-lean optimization profile perfect for Mobile, Nintendo Switch, or stylized PC/Console titles.\n\nTechnical Breakdown:\n- Budget: 10K Tris\n- Texturing: 2K PBR texture workflow\n- Pipeline:  Modern mobile, cross-platform, or lightweight gameplay pipelines.\n- Target Platforms - Mobile, Nintendo Switch, or stylized PC/Console titles", "tags": [], "src": "https://brothersinteractive.com/projects/mAnNrv", "w": 1000, "h": 891},
    {"t": "SWAT V2", "c": "realistic-humans", "id": "dyKqQQ", "i": "assets/img/portfolio/swat-v2-dykqqq.webp", "imgs": ["assets/img/portfolio/swat-v2-dykqqq-2.webp", "assets/img/portfolio/swat-v2-dykqqq-3.webp", "assets/img/portfolio/swat-v2-dykqqq-4.webp"], "desc": "Realistic Tactical Character Study: \"SWAT V2\"\nDeveloped internally at Brothers Interactive, \"SWAT V2\" represents our team's expertise in high-fidelity military realism and complex hard-surface character art. This production-ready asset was built from the ground up to showcase advanced material layering, intricate tactical gear details, and precise textile definition required for modern action and shooter titles.\n\nTechnical Breakdown:\n- Budget: 60K Tris \n- Texturing: PBR workflow, 4K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully rigged and tested with production motion data, ready for seamless integration into modern AAA gameplay and cinematic engines.", "tags": [], "src": "https://brothersinteractive.com/projects/dyKqQQ", "w": 1000, "h": 821},
    {"t": "Twin Witch", "c": "mid-night-walk", "id": "lEVXGY", "i": "assets/img/portfolio/twin-witch-levxgy.webp", "imgs": [], "desc": "The Midnight Walk- Twin Witch\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/lEVXGY", "w": 1000, "h": 889},
    {"t": "SWAT V3", "c": "realistic-humans", "id": "RKX2Ly", "i": "assets/img/portfolio/swat-v3-rkx2ly.webp", "imgs": ["assets/img/portfolio/swat-v3-rkx2ly-2.webp", "assets/img/portfolio/swat-v3-rkx2ly-3.webp", "assets/img/portfolio/swat-v3-rkx2ly-4.webp"], "desc": "Realistic Tactical Character Study: \"Female SWAT 3\"\nDeveloped internally at Brothers Interactive, \"Female SWAT 3\" represents our team's elite proficiency in high-fidelity military realism and complex, current-gen character art. This production-ready asset was built from the ground up to showcase premier material layering, intricate multi-part tactical gear, and the precise textile definition required for modern AAA action, shooter, and cinematic titles.\n\nTechnical Breakdown:\n- Budget: 142K Tris\n- Texturing: PBR workflow, five 4K and two 2K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully rigged and tested with production motion data, ready for seamless integration into modern AAA gameplay and cinematic engines.\n\nThanks", "tags": [], "src": "https://brothersinteractive.com/projects/RKX2Ly", "w": 1000, "h": 855},
    {"t": "Tiger (TLR-1)", "c": "realistic-creatures", "id": "LRG1Lk", "i": "assets/img/portfolio/tiger-tlr-1-lrg1lk.webp", "imgs": ["assets/img/portfolio/tiger-tlr-1-lrg1lk-2.webp", "assets/img/portfolio/tiger-tlr-1-lrg1lk-3.webp", "assets/img/portfolio/tiger-tlr-1-lrg1lk-4.webp"], "desc": "Stylized Creature Study: \"Tiger\"\nDeveloped internally at Brothers Interactive, \"Tiger\" represents our team's advanced capabilities in high-fidelity creature art and real-time shader pipelines. This production-ready asset was built from the ground up to showcase complex organic forms, stylized emissive accents, and a highly customizable material setup optimized for current-gen cinematic and gameplay engines.\n\nTechnical Breakdown:\n- Budget: 55K Tris\n- Texturing: Channel-packed mask map workflow, utilizing six 4K and two 2K texture sets to drive real-time engine shaders.\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Built specifically for an Unreal Engine pipeline; all primary material properties, color variations, and emissive elements are controlled dynamically via master shaders using our optimized mask maps", "tags": [], "src": "https://brothersinteractive.com/projects/LRG1Lk", "w": 1000, "h": 703},
    {"t": "Craftsman", "c": "mid-night-walk", "id": "lEVXDY", "i": "assets/img/portfolio/craftsman-levxdy.webp", "imgs": [], "desc": "The Midnight Walk- Craftman\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/lEVXDY", "w": 1000, "h": 825},
    {"t": "Princess", "c": "mid-night-walk", "id": "xdzK3r", "i": "assets/img/portfolio/princess-xdzk3r.webp", "imgs": [], "desc": "The Midnight Walk- Princess\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/xdzK3r", "w": 1000, "h": 981},
    {"t": "Big Bad Wolf", "c": "stylized-creature", "id": "rl0Xea", "i": "assets/img/portfolio/big-bad-wolf-rl0xea.webp", "imgs": ["assets/img/portfolio/big-bad-wolf-rl0xea-2.webp", "assets/img/portfolio/big-bad-wolf-rl0xea-3.webp", "assets/img/portfolio/big-bad-wolf-rl0xea-4.webp"], "desc": "Stylized Creature Study: \"Big Bad Wolf\"\nDeveloped internally at Brothers Interactive, \"Big Bad Wolf\" represents our team's talent for expressive, animated creature design and stylized character art. This production-ready asset was built from the ground up to showcase a strong silhouette, dynamic personality, and clean shape language perfect for modern fantasy, adventure, or strategy titles.\nBad Wolf Fanart from nicola saviori -https://www.artstation.com/nicolasaviori\n\nTechnical Breakdown:\nBudget: 13K Tris\nTexturing: PBR workflow, single 2K texture set\nTarget Platforms: Mobile, Nintendo Switch, and PC\nPipeline: Fully optimized with clean, deformation-ready topology, ready for seamless integration into modern low-spec and cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/rl0Xea", "w": 1000, "h": 682},
    {"t": "Crow Mother", "c": "mid-night-walk", "id": "wO850X", "i": "assets/img/portfolio/crow-mother-wo850x.webp", "imgs": [], "desc": "The Midnight Walk- Crow Mother\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/wO850X", "w": 1000, "h": 557},
    {"t": "Zombie-2", "c": "realistic-creatures", "id": "rJVn4e", "i": "assets/img/portfolio/zombie-2-rjvn4e.webp", "imgs": ["assets/img/portfolio/zombie-2-rjvn4e-2.webp", "assets/img/portfolio/zombie-2-rjvn4e-3.webp", "assets/img/portfolio/zombie-2-rjvn4e-4.webp"], "desc": "Cinematic Character Study: \"Zombie - 2\"\nDeveloped internally at Brothers Interactive, \"Zombie - 2\" represents our team's proficiency in organic horror sculpting, advanced tissue deformation, and high-end texture weathering. This production-ready asset was built from the ground up to showcase hyper-detailed organic trauma, realistic anatomical decay, and complex fabric distressing required for current-gen horror, survival, and action titles.\n\nTechnical Breakdown:\n- Budget: 120K Tris\n- Texturing: PBR workflow, four 4K, two 2K, and one 1K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for current-gen cinematic and gameplay engines, utilizing an advanced high-to-low poly baking pipeline to capture fine micro-surface tissue details (Optimized for enemy/boss gameplay assets, survival-horror mechanics, and real-time cinematic cutscenes).\n\nThanks", "tags": [], "src": "https://brothersinteractive.com/projects/rJVn4e", "w": 1000, "h": 864},
    {"t": "Orc", "c": "stylized-creature", "id": "qJY3qa", "i": "assets/img/portfolio/orc-qjy3qa.webp", "imgs": ["assets/img/portfolio/orc-qjy3qa-2.webp", "assets/img/portfolio/orc-qjy3qa-3.webp", "assets/img/portfolio/orc-qjy3qa-4.webp"], "desc": "Stylized Fantasy Character Study: \"Orc\"\nDeveloped internally at Brothers Interactive, \"Orc\" represents our team's expertise in high-quality stylized creature and character art. This production-ready asset was built from the ground up to showcase bold silhouette readability, expressive anatomical proportions, and vibrant material definition required for modern stylized fantasy and strategy titles.\n\nTechnical Breakdown:\n- Budget: 11,900 Tris\n- Texturing: PBR workflow, single 2K texture set\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology, ready for seamless integration into modern low-spec and cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/qJY3qa", "w": 1000, "h": 900},
    {"t": "Father Murkle", "c": "mid-night-walk", "id": "KRaBex", "i": "assets/img/portfolio/father-murkle-krabex.webp", "imgs": [], "desc": "Father Murkle by Brothers Interactive.", "tags": [], "src": "https://brothersinteractive.com/projects/KRaBex", "w": 1000, "h": 576},
    {"t": "MTG Krishna", "c": "realistic-humans", "id": "yD5Ll3", "i": "assets/img/portfolio/mtg-krishna-yd5ll3.webp", "imgs": ["assets/img/portfolio/mtg-krishna-yd5ll3-2.webp", "assets/img/portfolio/mtg-krishna-yd5ll3-3.webp", "assets/img/portfolio/mtg-krishna-yd5ll3-4.webp"], "desc": "Cinematic Character Study: \"MTG - Krishna\"\nDeveloped internally at Brothers Interactive, \"Krishna\" represents our team's peak proficiency in hyper-realistic digital human creation and high-end cinematic art. This production-ready asset was built from the ground up to showcase intricate hard-surface jewelry, complex multi-layered textile garments, and advanced strand-based grooming workflows required for premier current-gen titles and cinematic narratives.\n\nTechnical Breakdown:\n- Budget: 513K Tris\n- Texturing: PBR workflow, five 4K, three 2K, and one 1K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for current-gen cinematic engines, utilizing an advanced Alembic strand-based hair workflow for realistic, dynamic hair physics simulations (Optimized for hero gameplay assets, next-gen cutscenes, and high-end cinematics)..", "tags": [], "src": "https://brothersinteractive.com/projects/yD5Ll3", "w": 1000, "h": 788},
    {"t": "Zombie-1", "c": "realistic-creatures", "id": "qezJmN", "i": "assets/img/portfolio/zombie-1-qezjmn.webp", "imgs": ["assets/img/portfolio/zombie-1-qezjmn-2.webp", "assets/img/portfolio/zombie-1-qezjmn-3.webp", "assets/img/portfolio/zombie-1-qezjmn-4.webp"], "desc": "Cinematic Character Study: \"Zombie - 1\"\nDeveloped internally at Brothers Interactive, \"Zombie - 1\" represents our team's proficiency in organic horror sculpting, advanced tissue deformation, and high-end texture weathering. This production-ready asset was built from the ground up to showcase hyper-detailed organic trauma, realistic anatomical decay, and complex fabric distressing required for current-gen horror, survival, and action titles.\n\nTechnical Breakdown:\n- Budget: 80K Tris\n- Texturing: PBR workflow, four 4K, two 2K, and one 1K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for current-gen cinematic and gameplay engines, utilizing an advanced high-to-low poly baking pipeline to capture fine micro-surface tissue details (Optimized for enemy/boss gameplay assets, survival-horror mechanics, and real-time cinematic cutscenes).\n\nThanks", "tags": [], "src": "https://brothersinteractive.com/projects/qezJmN", "w": 1000, "h": 720},
    {"t": "Grandma Dark", "c": "mid-night-walk", "id": "0aXrlE", "i": "assets/img/portfolio/grandma-dark-0axrle.webp", "imgs": [], "desc": "The Midnight Walk- Grandma Dark\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/0aXrlE", "w": 1000, "h": 567},
    {"t": "Crow", "c": "mid-night-walk", "id": "dLORKw", "i": "assets/img/portfolio/crow-dlorkw.webp", "imgs": [], "desc": "The Midnight Walk- Crow\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/dLORKw", "w": 1000, "h": 767},
    {"t": "SWAT V1", "c": "realistic-humans", "id": "YGBQbY", "i": "assets/img/portfolio/swat-v1-ygbqby.webp", "imgs": ["assets/img/portfolio/swat-v1-ygbqby-2.webp", "assets/img/portfolio/swat-v1-ygbqby-3.webp", "assets/img/portfolio/swat-v1-ygbqby-4.webp"], "desc": "Realistic Tactical Character Study: \"SWAT V2\"\nDeveloped internally at Brothers Interactive, \"SWAT V2\" represents our team's expertise in high-fidelity military realism and complex hard-surface character art. This production-ready asset was built from the ground up to showcase advanced material layering, intricate tactical gear details, and precise textile definition required for modern action and shooter titles.\n\nTechnical Breakdown:\n- Budget: 65K Tris\n- Texturing: PBR workflow, 4K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully rigged and tested with production motion data, ready for seamless integration into modern AAA gameplay and cinematic engines.", "tags": [], "src": "https://brothersinteractive.com/projects/YGBQbY", "w": 1000, "h": 761},
    {"t": "Pot Boy", "c": "props", "id": "ayRb09", "i": "assets/img/portfolio/pot-boy-ayrb09.webp", "imgs": ["assets/img/portfolio/pot-boy-ayrb09-2.webp"], "desc": "The Midnight Walk- Pot Boy\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/ayRb09", "w": 1000, "h": 750},
    {"t": "Four Witch", "c": "mid-night-walk", "id": "G1XVva", "i": "assets/img/portfolio/four-witch-g1xvva.webp", "imgs": ["assets/img/portfolio/four-witch-g1xvva-2.webp"], "desc": "The Midnight Walk- Four Witch\n\nAt Brothers Interactive, we contributed character cleanup, Sculpt &amp; Texture Improvements, game res version and rigging services for multiple characters featured in The Midnight Walk, helping prepare scanned character assets for integration and use within the game pipeline.\n\nOur work focused on optimizing character assets, technical cleanup, and rigging support to ensure the characters were production-ready for gameplay implementation.", "tags": [], "src": "https://brothersinteractive.com/projects/G1XVva", "w": 1000, "h": 652},
    {"t": "Shark (TLR-1)", "c": "realistic-creatures", "id": "QX2OBd", "i": "assets/img/portfolio/shark-tlr-1-qx2obd.webp", "imgs": ["assets/img/portfolio/shark-tlr-1-qx2obd-2.webp", "assets/img/portfolio/shark-tlr-1-qx2obd-3.webp", "assets/img/portfolio/shark-tlr-1-qx2obd-4.webp"], "desc": "Stylized Creature Study: \"Shark\"\nDeveloped internally at Brothers Interactive, \"Shark\" represents our team's advanced capabilities in high-fidelity creature art and real-time shader pipelines. This production-ready asset was built from the ground up to showcase powerful organic forms, dynamic emissive accents, and a highly customizable material setup optimized for current-gen cinematic and gameplay engines.\n\nTechnical Breakdown:\n- Budget: 60K Tris\n- Texturing: Channel-packed mask map workflow, utilizing six 4K and two 2K texture sets to drive real-time engine shaders.\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Built specifically for an Unreal Engine pipeline; all primary material properties, color variations, and emissive elements are controlled dynamically via master shaders using our optimized mask maps.\n\nThanks", "tags": [], "src": "https://brothersinteractive.com/projects/QX2OBd", "w": 1000, "h": 1034},
    {"t": "Panda (TLR-1)", "c": "realistic-creatures", "id": "PXvoWo", "i": "assets/img/portfolio/panda-tlr-1-pxvowo.webp", "imgs": ["assets/img/portfolio/panda-tlr-1-pxvowo-2.webp", "assets/img/portfolio/panda-tlr-1-pxvowo-3.webp", "assets/img/portfolio/panda-tlr-1-pxvowo-4.webp"], "desc": "Stylized Creature Study: \"Panda\"\nDeveloped internally at Brothers Interactive, \"Panda\" represents our team's advanced capabilities in high-fidelity creature art and real-time shader pipelines. This production-ready asset was built from the ground up to showcase powerful organic forms, dynamic structural design, and a highly customizable material setup optimized for current-gen cinematic and gameplay engines.\n\nTechnical Breakdown:\n- Budget: 55K Tris\n- Texturing: Channel-packed mask map workflow, utilizing six 4K and two 2K texture sets to drive real-time engine shaders.\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Built specifically for an Unreal Engine pipeline; all primary material properties, color variations, and emissive elements are controlled dynamically via master shaders using our optimized mask maps.", "tags": [], "src": "https://brothersinteractive.com/projects/PXvoWo", "w": 1000, "h": 638},
    {"t": "Turtle (TLR-1)", "c": "realistic-creatures", "id": "ZavKOG", "i": "assets/img/portfolio/turtle-tlr-1-zavkog.webp", "imgs": ["assets/img/portfolio/turtle-tlr-1-zavkog-2.webp", "assets/img/portfolio/turtle-tlr-1-zavkog-3.webp", "assets/img/portfolio/turtle-tlr-1-zavkog-4.webp"], "desc": "Stylized Creature Study: \"Turtle\"\nDeveloped internally at Brothers Interactive, \"Turtle\" represents our team's advanced capabilities in high-fidelity creature art and real-time shader pipelines. This production-ready asset was built from the ground up to showcase dense organic forms, rugged shell structures, and a highly customizable material setup optimized for current-gen cinematic and gameplay engines.\n\nTechnical Breakdown:\n- Budget: 55K Tris\n- Texturing: Channel-packed mask map workflow, utilizing six 4K and two 2K texture sets to drive real-time engine shaders.\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Built specifically for an Unreal Engine pipeline; all primary material properties, color variations, and surface elements are controlled dynamically via master shaders using our optimized mask maps.", "tags": [], "src": "https://brothersinteractive.com/projects/ZavKOG", "w": 1000, "h": 990},
    {"t": "MTG Murkaz Tex", "c": "realistic-creatures", "id": "lDNWka", "i": "assets/img/portfolio/mtg-murkaz-tex-ldnwka.webp", "imgs": ["assets/img/portfolio/mtg-murkaz-tex-ldnwka-2.webp", "assets/img/portfolio/mtg-murkaz-tex-ldnwka-3.webp", "assets/img/portfolio/mtg-murkaz-tex-ldnwka-4.webp"], "desc": "Cinematic Character Study: \"Murkaz\"\nDeveloped internally at Brothers Interactive, \"Murkaz\" represents our team's peak proficiency in hyper-realistic dark fantasy creature creation and high-end cinematic art. This production-ready asset was built from the ground up to showcase complex organic anatomy, heavily weathered hard-surface armor, and advanced real-time grooming workflows required for premier current-gen titles and cinematic narratives.\n\nTechnical Breakdown:\n- Budget: 320K Tris\n- Texturing: PBR workflow, eight 4K and three 2K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for current-gen engines, utilizing an advanced real-time alpha card hair and fur method for dense, high-fidelity shading and physics integration (Optimized for boss gameplay assets, next-gen cutscenes, and high-end cinematics).", "tags": [], "src": "https://brothersinteractive.com/projects/lDNWka", "w": 1000, "h": 1000},
    {"t": "Beatle - Crash Bandicoot 4 Fanart", "c": "stylized-creature", "id": "zxBExq", "i": "assets/img/portfolio/beatle-crash-bandicoot-4-fanart-zxbexq.webp", "imgs": ["assets/img/portfolio/beatle-crash-bandicoot-4-fanart-zxbexq-2.webp", "assets/img/portfolio/beatle-crash-bandicoot-4-fanart-zxbexq-3.webp", "assets/img/portfolio/beatle-crash-bandicoot-4-fanart-zxbexq-4.webp"], "desc": "Stylized Creature Study: \"Beetle\"\nDeveloped internally at Brothers Interactive, \"Beetle\" represents our team's capability in stylized insect and creature design. This production-ready asset was built from the ground up to showcase bold shell silhouettes, distinct carapace segmentation, and vibrant material definition required for modern fantasy, adventure, or RPG titles.\n\nTechnical Breakdown:\n- Budget: 10K Tris\n- Texturing: PBR workflow, single 2K texture set\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology, ready for seamless integration into modern low-spec and cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/zxBExq", "w": 1000, "h": 882},
    {"t": "Lehri", "c": "realistic-humans", "id": "dKWXLA", "i": "assets/img/portfolio/lehri-dkwxla.webp", "imgs": ["assets/img/portfolio/lehri-dkwxla-2.webp", "assets/img/portfolio/lehri-dkwxla-3.webp", "assets/img/portfolio/lehri-dkwxla-4.webp"], "desc": "Cinematic Character Study: \"Lehri\"\nDeveloped internally at Brothers Interactive, \"Lehri\" represents our team's proficiency in realistic human character creation, expressive facial sculpting, and authentic textile definition. This production-ready asset was built from the ground up to showcase high-fidelity skin micro-structures, detailed multi-layered cultural garments, and precise material aging required for premier current-gen titles and narrative-driven experiences.\n\nTechnical Breakdown:\n- Budget: 107K Tris\n- Texturing: PBR workflow, five 4K and two 2K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for current-gen cinematic and gameplay engines, ensuring clean topology for facial deformation and complex cloth simulation workflows (Optimized for main/supporting character gameplay assets, next-gen cutscenes, and high-end cinematics).", "tags": [], "src": "https://brothersinteractive.com/projects/dKWXLA", "w": 1000, "h": 1000},
    {"t": "CHR Skins", "c": "realistic-humans", "id": "GeVBoB", "i": "assets/img/portfolio/chr-skins-gevbob.webp", "imgs": ["assets/img/portfolio/chr-skins-gevbob-2.webp", "assets/img/portfolio/chr-skins-gevbob-3.webp", "assets/img/portfolio/chr-skins-gevbob-4.webp"], "desc": "Character Customization Study: \"CHR Skins\"\nDeveloped internally at Brothers Interactive, \"CHR Skins\" represents our team's proficiency in creating modular character cosmetic variations, modern apparel design, and highly efficient production pipelines. This asset package was built from the ground up to showcase distinct textile definition, trendy streetwear aesthetics, and optimized multi-layered clothing assets required for modern live-service and multiplayer titles.\n\nTechnical Breakdown:\n- Budget: 35K Tris (Average per full character outfit skin)\n- Texturing: PBR workflow, two 4K sets for apparel and one 2K set specifically for footwear\n- Target Platforms: PC, PlayStation 5, Xbox Series X|S, and Cross-Platform Multiplayer\n- Pipeline: Fully optimized for modular character customization systems, featuring clean topology ready for skin-weighting, dynamic cloth simulations, and high-volume live-service asset integration (Optimized for multiplayer cosmetic skins, battle pass rewards, and player customization systems).\n\nThanks", "tags": [], "src": "https://brothersinteractive.com/projects/GeVBoB", "w": 1000, "h": 605},
    {"t": "Female Hair", "c": "realistic-hairs", "id": "XJgvnn", "i": "assets/img/portfolio/female-hair-xjgvnn.webp", "imgs": ["assets/img/portfolio/female-hair-xjgvnn-2.webp", "assets/img/portfolio/female-hair-xjgvnn-3.webp", "assets/img/portfolio/female-hair-xjgvnn-4.webp"], "desc": "Real-Time Grooming Study: \"Female Hair\"\nDeveloped internally at Brothers Interactive, \"Hair Variations\" represents our team's specialized proficiency in advanced real-time hair creation, intricate grooming layouts, and high-fidelity shader integration. This asset package was built from the ground up to showcase clean strand flow, complex layering, and exceptional silhouette definition required for modern current-gen characters and digital humans.\n\nTechnical Breakdown:\n- Budget: 60K Tris\n- Texturing: PBR workflow, single 4K texture set optimized for hair shaders\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for modern real-time hair pipelines, utilizing a clean, high-performance alpha card layout to ensure realistic depth, light scattering, and dynamic physics/wind simulation integration (Optimized for main hero characters, customizable customization systems, and current-gen gameplay).", "tags": [], "src": "https://brothersinteractive.com/projects/XJgvnn", "w": 1000, "h": 1000},
    {"t": "Male Hairs Variations", "c": "realistic-hairs", "id": "L4EZxw", "i": "assets/img/portfolio/male-hairs-variations-l4ezxw.webp", "imgs": ["assets/img/portfolio/male-hairs-variations-l4ezxw-2.webp", "assets/img/portfolio/male-hairs-variations-l4ezxw-3.webp", "assets/img/portfolio/male-hairs-variations-l4ezxw-4.webp"], "desc": "Real-Time Grooming Study: \"Male Hair Variations\"\nDeveloped internally at Brothers Interactive, \"Male Hair Variations\" represents our team's specialized proficiency in advanced real-time hair creation, scalable grooming layouts, and highly optimized asset budgets. This asset package was built from the ground up to showcase a multi-stage production pipeline, featuring varying structural densities and clean strand flow required for modern character customization or progressive visual styling.\n\nTechnical Breakdown:\n- Budget: Progressive multi-stage optimization layout:\n                 Stage 1: 45K Tris \n                 Stage 2: 38K Tris\n                 Stage 3: 35K Tris\n                 Stage 4: 30K Tris\n                 Stage 5: 25K Tris \n- Texturing: PBR workflow, single 4K texture set\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for flexible character customization systems, utilizing a high-performance alpha card layout designed to scale fluidly across different gameplay performance targets while retaining realistic depth and dynamic physics integration.", "tags": [], "src": "https://brothersinteractive.com/projects/L4EZxw", "w": 1000, "h": 850},
    {"t": "Kart", "c": "props", "id": "lGYlmV", "i": "assets/img/portfolio/kart-lgylmv.webp", "imgs": ["assets/img/portfolio/kart-lgylmv-2.webp", "assets/img/portfolio/kart-lgylmv-3.webp", "assets/img/portfolio/kart-lgylmv-4.webp"], "desc": "Stylized Vehicle Study: \"Kart\"\nDeveloped internally at Brothers Interactive, \"Kart\" represents our team's proficiency in stylized hard-surface vehicle design, mechanical silhouette composition, and optimized prop modeling. This production-ready asset was built from the ground up to showcase bold geometric forms, clean material separation, and high-impact arcade aesthetics required for modern racing, action, and multiplayer titles.\n\nTechnical Breakdown:\n- Budget: 29K Tris\n- Texturing: PBR workflow, single 4K texture set\n- Target Platforms: PC, PlayStation 5, Xbox Series X|S, and Nintendo Switch\n- Pipeline: Fully optimized with clean mechanical topology, featuring distinct material IDs and proper pivot orientation.", "tags": [], "src": "https://brothersinteractive.com/projects/lGYlmV", "w": 1000, "h": 807},
    {"t": "Toothbug", "c": "realistic-creatures", "id": "LR56mr", "i": "assets/img/portfolio/toothbug-lr56mr.webp", "imgs": ["assets/img/portfolio/toothbug-lr56mr-2.webp", "assets/img/portfolio/toothbug-lr56mr-3.webp", "assets/img/portfolio/toothbug-lr56mr-4.webp"], "desc": "Stylized Creature Study: \"Tooth Bug\"\nDeveloped internally at Brothers Interactive, \"Tooth Bug\" represents our team's talent for expressive creature design, unique character concepts, and clean shape language. This production-ready asset was built from the ground up to showcase bold anatomical silhouettes, vibrant material definitions, and high-impact personality required for modern fantasy, adventure, or strategy titles.\nConcept art by Tooth Wu!", "tags": [], "src": "https://brothersinteractive.com/projects/LR56mr", "w": 1000, "h": 720},
    {"t": "Death", "c": "lost-in-random", "id": "5BW8y8", "i": "assets/img/portfolio/death-5bw8y8.webp", "imgs": ["assets/img/portfolio/death-5bw8y8-2.webp"], "desc": "Death\n\nAnother character work from LOST IN RANDOM.\nAnd our team members, who contributed.\n- Arun Nagar\n- Rajat Sharma\n- Sohail Khan\n- Krishna Paswan\nThanks!\n\nWebsite -http://brothersinteractive.com/\nLinkedin - https://www.linkedin.com/company/brothers-interactive\nArtstation - https://www.artstation.com/brothersinteractive\nFacebook - https://www.facebook.com/Brothersinteractive\nInstagram - https://www.instagram.com/brothersinteractive/", "tags": [], "src": "https://brothersinteractive.com/projects/5BW8y8", "w": 512, "h": 512},
    {"t": "Rug Reader", "c": "lost-in-random", "id": "4Xb69l", "i": "assets/img/portfolio/rug-reader-4xb69l.webp", "imgs": ["assets/img/portfolio/rug-reader-4xb69l-2.webp", "assets/img/portfolio/rug-reader-4xb69l-3.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/4Xb69l", "w": 512, "h": 512},
    {"t": "Lost in Random - Gunner", "c": "lost-in-random", "id": "0n1wgV", "i": "assets/img/portfolio/lost-in-random-gunner-0n1wgv.webp", "imgs": ["assets/img/portfolio/lost-in-random-gunner-0n1wgv-2.webp", "assets/img/portfolio/lost-in-random-gunner-0n1wgv-3.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/0n1wgV", "w": 400, "h": 400},
    {"t": "Baroness", "c": "lost-in-random", "id": "EaLNv2", "i": "assets/img/portfolio/baroness-ealnv2.webp", "imgs": ["assets/img/portfolio/baroness-ealnv2-2.webp", "assets/img/portfolio/baroness-ealnv2-3.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/EaLNv2", "w": 512, "h": 512},
    {"t": "Neeshka", "c": "lost-in-random", "id": "6bv986", "i": "assets/img/portfolio/neeshka-6bv986.webp", "imgs": [], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/6bv986", "w": 400, "h": 400},
    {"t": "Bag Monster", "c": "lost-in-random", "id": "144Kve", "i": "assets/img/portfolio/bag-monster-144kve.webp", "imgs": ["assets/img/portfolio/bag-monster-144kve-2.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/144Kve", "w": 512, "h": 512},
    {"t": "McBiggo", "c": "lost-in-random", "id": "4X1Eq4", "i": "assets/img/portfolio/mcbiggo-4x1eq4.webp", "imgs": ["assets/img/portfolio/mcbiggo-4x1eq4-2.webp", "assets/img/portfolio/mcbiggo-4x1eq4-3.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/4X1Eq4", "w": 512, "h": 512},
    {"t": "Janitor", "c": "lost-in-random", "id": "KOeZEW", "i": "assets/img/portfolio/janitor-koezew.webp", "imgs": ["assets/img/portfolio/janitor-koezew-2.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/KOeZEW", "w": 512, "h": 512},
    {"t": "RobotDuke", "c": "lost-in-random", "id": "8w1KXn", "i": "assets/img/portfolio/robotduke-8w1kxn.webp", "imgs": ["assets/img/portfolio/robotduke-8w1kxn-2.webp", "assets/img/portfolio/robotduke-8w1kxn-3.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/8w1KXn", "w": 512, "h": 512},
    {"t": "Potion Maker 01", "c": "lost-in-random", "id": "b5gv3v", "i": "assets/img/portfolio/potion-maker-01-b5gv3v.webp", "imgs": ["assets/img/portfolio/potion-maker-01-b5gv3v-2.webp"], "desc": "We are proud to share the first game project our studio ever contributed, \"LOST IN RANDOM\".\nThanks Zoink games for trusting us.", "tags": [], "src": "https://brothersinteractive.com/projects/b5gv3v", "w": 512, "h": 512},
    {"t": "Bag Brother", "c": "lost-in-random", "id": "Peowg3", "i": "assets/img/portfolio/bag-brother-peowg3.webp", "imgs": ["assets/img/portfolio/bag-brother-peowg3-2.webp", "assets/img/portfolio/bag-brother-peowg3-3.webp"], "desc": "Bag Brother\n\nAnother character work from LOST IN RANDOM.\nAnd our team members, who contributed.\n- Arun Nagar\n- Rajat Sharma\n- Sohail Khan\n- Krishna Paswan\nThanks!\n\nWebsite -http://brothersinteractive.com/\nLinkedin - https://www.linkedin.com/company/brothers-interactive\nArtstation - https://www.artstation.com/brothersinteractive\nFacebook - https://www.facebook.com/Brothersinteractive\nInstagram - https://www.instagram.com/brothersinteractive/", "tags": [], "src": "https://brothersinteractive.com/projects/Peowg3", "w": 512, "h": 512},
    {"t": "Russell Del's Girl CHR", "c": "stylized-human", "id": "L3A48w", "i": "assets/img/portfolio/russell-del-s-girl-chr-l3a48w.webp", "imgs": ["assets/img/portfolio/russell-del-s-girl-chr-l3a48w-2.webp", "assets/img/portfolio/russell-del-s-girl-chr-l3a48w-3.webp", "assets/img/portfolio/russell-del-s-girl-chr-l3a48w-4.webp"], "desc": "Stylized Character Study: \"Russell Del's Girl\"\nDeveloped internally at Brothers Interactive, \"Russell Del's Girl\" represents our team's talent for expressive stylized character modeling, clean shape translation, and high-efficiency production pipelines. This production-ready asset was built from the ground up to showcase elegant silhouettes, charming facial proportions, and vibrant material definition required for modern animated adventure, RPG, or stylized action titles.\n\nTechnical Breakdown:\n- Budget: 25K Tris\n- Texturing: PBR workflow, two 2K texture sets\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology and structured facial loops, ready for seamless rigging, performance animation, and integration into modern cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/L3A48w", "w": 1000, "h": 938},
    {"t": "Russell Del's Boy CHR", "c": "stylized-human", "id": "zOaxkD", "i": "assets/img/portfolio/russell-del-s-boy-chr-zoaxkd.webp", "imgs": ["assets/img/portfolio/russell-del-s-boy-chr-zoaxkd-2.webp", "assets/img/portfolio/russell-del-s-boy-chr-zoaxkd-3.webp", "assets/img/portfolio/russell-del-s-boy-chr-zoaxkd-4.webp"], "desc": "Stylized Character Study: \"Russell Del's Girl\"\nDeveloped internally at Brothers Interactive, \"Russell Del's Girl\" represents our team's talent for expressive stylized character modeling, clean shape translation, and high-efficiency production pipelines. This production-ready asset was built from the ground up to showcase elegant silhouettes, charming facial proportions, and vibrant material definition required for modern animated adventure, RPG, or stylized action titles.\n\nTechnical Breakdown:\n- Budget: 21K Tris\n- Texturing: PBR workflow, two 2K texture sets\n- Target Platforms: Mobile, Nintendo Switch, and PC\n- Pipeline: Fully optimized with clean, deformation-ready topology and structured facial loops, ready for seamless rigging, performance animation, and integration into modern cross-platform gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/zOaxkD", "w": 1000, "h": 774},
    {"t": "Sir Galahad : The Order 1886 Fanart", "c": "realistic-humans", "id": "B1nbk8", "i": "assets/img/portfolio/sir-galahad-the-order-1886-fanart-b1nbk8.webp", "imgs": ["assets/img/portfolio/sir-galahad-the-order-1886-fanart-b1nbk8-2.webp", "assets/img/portfolio/sir-galahad-the-order-1886-fanart-b1nbk8-3.webp", "assets/img/portfolio/sir-galahad-the-order-1886-fanart-b1nbk8-4.webp"], "desc": "Cinematic Character Study: \"Sir Galahad\" (The Order 1886 Fanart)\nDeveloped internally at Brothers Interactive, \"Sir Galahad\" represents our team's proficiency in replicating complex AAA cinematic character designs, advanced hard-surface armor integration, and realistic fabric weathering. This production-ready asset was built from the ground up to showcase multi-layered historical tailoring, intricate metallic ornaments, and dense material realism required for premier current-gen action and narrative titles.\n\nTechnical Breakdown:\n- Budget: 160K Tris\n- Texturing: PBR workflow, two 4K and eight 2K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized for current-gen cinematic and gameplay engines, ensuring clean topology for heavy cloth simulation and rigid hard-surface deformation workflows (Optimized for hero gameplay assets, next-gen cutscenes, and high-end cinematics).", "tags": [], "src": "https://brothersinteractive.com/projects/B1nbk8", "w": 1000, "h": 562},
    {"t": "Adam - Game Res Model", "c": "stylized-human", "id": "B1e5nm", "i": "assets/img/portfolio/adam-game-res-model-b1e5nm.webp", "imgs": ["assets/img/portfolio/adam-game-res-model-b1e5nm-2.webp", "assets/img/portfolio/adam-game-res-model-b1e5nm-3.webp", "assets/img/portfolio/adam-game-res-model-b1e5nm-4.webp"], "desc": "Progressive Character Study: \"Adam\"\nDeveloped internally at Brothers Interactive, \"Adam\" represents our team's proficiency in creating modular character progression systems, progressive armor tiering, and highly efficient production workflows. This game-ready asset showcases a 5-stage evolutionary pipeline, built from the ground up to demonstrate how a character can seamlessly scale from a base level to an advanced endgame warrior while maintaining strict optimization for low-end performance brackets.\n\nCharacter Progression Pipeline:\n- 1st Level: Base schoolboy archetype.\n- 2nd Level: Rebel tier with light guerrilla combat gear additions.\n- 3rd Level: Ranged combat specialization featuring specialized bow and arrow equipment.\n- 4th Level: Melee combat tier integrating lightweight sword-fighting gear and armor pieces.\n- 5th Level: Elite warrior tier fully equipped for one-on-one boss encounters.\n\nTechnical Breakdown:\n- Budget: Highly optimized low-end triangle budget across all modular tiers\n- Texturing: PBR workflow, single 2K base texture map with scalable supporting map slots added per equipment tier requirement\n- Target Platforms: Mobile, Nintendo Switch, PC, and Cross-Platform Multiplayer\n- Pipeline: Fully optimized with a unified base skeleton and clean deformation topology, engineered for seamless modular attachment swapping, progressive visual upgrades, and fluid integration into real-time gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/B1e5nm", "w": 1000, "h": 521},
    {"t": "Proposal Book", "c": "props", "id": "KaQZrr", "i": "assets/img/portfolio/proposal-book-kaqzrr.webp", "imgs": ["assets/img/portfolio/proposal-book-kaqzrr-2.webp", "assets/img/portfolio/proposal-book-kaqzrr-3.webp", "assets/img/portfolio/proposal-book-kaqzrr-4.webp"], "desc": "Ornate Prop Study: \"Proposal Book\"\nDeveloped internally at Brothers Interactive, we finished 12 week long masterclass in 2019 about gaming pipeline for props. \n\nProduction Concept:\nAn ancient, masterfully crafted heavy tome featuring prominent, hand-forged metallic scrollwork and defensive metal plates layered across a weathered leather binding, anchored by a central embedded magical gemstone.\n\nTechnical Breakdown:\n- Budget: Fully optimized current-gen prop triangle budget\n- Texturing: High-fidelity PBR workflow, utilizing high-resolution texture sets to maximize micro-surface metallic scratch details, leather aging, and crystal refractivity\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized with clean hard-surface topology and precise material IDs, ready for seamless integration into close-up first-person viewports, narrative puzzle interactions, and current-gen gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/KaQZrr", "w": 1000, "h": 1000},
    {"t": "Fire Drum", "c": "props", "id": "XB3ExY", "i": "assets/img/portfolio/fire-drum-xb3exy.webp", "imgs": ["assets/img/portfolio/fire-drum-xb3exy-2.webp", "assets/img/portfolio/fire-drum-xb3exy-3.webp", "assets/img/portfolio/fire-drum-xb3exy-4.webp"], "desc": "Realistic Environment Prop Study: \"Fire Drum\"\nDeveloped internally at Brothers Interactive, \"Fire Drum\" represents our team's proficiency in high-fidelity prop modeling, advanced material degradation, and realistic surface weathering. This production-ready asset was built from the ground up to showcase intricate structural damage, complex oxidation patterns, and detailed ash/carbon texturing required for immersive current-gen survival, post-apocalyptic, and horror environments.\n\nTechnical Breakdown:\n- Budget: 14K Tris\n- Texturing: PBR workflow, three 2K texture sets separating the metal barrel, internal embers, and detailed wooden fuel elements\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized with clean hard-surface topology and optimized material IDs, ready for seamless integration into real-time particle/emissive setups and current-gen gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/XB3ExY", "w": 1000, "h": 800},
    {"t": "Pip-Boy 2000 - Game Res Asset", "c": "props", "id": "ybZDb8", "i": "assets/img/portfolio/pip-boy-2000-game-res-asset-ybzdb8.webp", "imgs": ["assets/img/portfolio/pip-boy-2000-game-res-asset-ybzdb8-2.webp", "assets/img/portfolio/pip-boy-2000-game-res-asset-ybzdb8-3.webp", "assets/img/portfolio/pip-boy-2000-game-res-asset-ybzdb8-4.webp"], "desc": "Realistic Prop Study: \"Pip-Boy\" (Fallout Fanart)\nDeveloped internally at Brothers Interactive, \"Pip-Boy\" represents our team's proficiency in retro-futuristic hard-surface modeling, industrial prop design, and complex surface weathering. This game-ready asset was built from the ground up to showcase mechanical complexity, analog component detailing, and realistic metallic wear required for premier sci-fi, RPG, and survival titles.\n\nTechnical Breakdown:\n- Budget: 8K Tris\n- Texturing: PBR workflow, single 2K texture set\n- Target Platforms: PC, PlayStation 5, Xbox Series X|S, and Nintendo Switch\n- Pipeline: Fully optimized with clean hard-surface topology and precise pivot setups for interactive components, ready for seamless integration into first-person viewport layouts, UI screen casting, and real-time gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/ybZDb8", "w": 1000, "h": 750},
    {"t": "Dhakad", "c": "realistic-humans", "id": "JXN6n", "i": "assets/img/portfolio/dhakad-jxn6n.webp", "imgs": ["assets/img/portfolio/dhakad-jxn6n-2.webp", "assets/img/portfolio/dhakad-jxn6n-3.webp", "assets/img/portfolio/dhakad-jxn6n-4.webp"], "desc": "Cinematic Portrait Study: \"Dhakad\"\nDeveloped internally at Brothers Interactive, \"Dhakad\" represents our team's proficiency in hyper-realistic digital human creation, expressive facial sculpting, and clean real-time hair card placement. This production-ready asset was built from the ground up to showcase subtle skin micro-structures, sharp anatomical proportions, and realistic light scattering required for modern narrative-driven and cinematic current-gen titles.\n\nTechnical Breakdown:\n- Budget: 42K Triangles Total (Optimized Split):\n                Head Mesh: 25K Tris\n                Hair Groom: 17K Tris\n- Texturing: PBR workflow, single 4K map for the head and single 2K map for the hair layout\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized with clean, deformation-ready facial topology, engineered for seamless integration into advanced rigging, facial blendshape pipelines, real-time dialogue cameras, and current-gen gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/JXN6n", "w": 1000, "h": 1000},
    {"t": "Head Study", "c": "realistic-humans", "id": "0QOke", "i": "assets/img/portfolio/head-study-0qoke.webp", "imgs": ["assets/img/portfolio/head-study-0qoke-2.webp", "assets/img/portfolio/head-study-0qoke-3.webp", "assets/img/portfolio/head-study-0qoke-4.webp"], "desc": "Head Study - Benedict wong\n\nDeveloped internally at Brothers Interactive, \"Head Study\" represents our team's foundational strength in hyper-realistic organic sculpting and secondary form definition. This high-poly asset was developed to showcase an advanced understanding of facial fat distribution, complex skin micro-detailing, and natural tissue weight distribution required for high-fidelity AAA character generation.", "tags": [], "src": "https://brothersinteractive.com/projects/0QOke", "w": 1000, "h": 735},
    {"t": "Rasch : Crysis 3 Fanart", "c": "realistic-humans", "id": "r3z0m", "i": "assets/img/portfolio/rasch-crysis-3-fanart-r3z0m.webp", "imgs": ["assets/img/portfolio/rasch-crysis-3-fanart-r3z0m-2.webp", "assets/img/portfolio/rasch-crysis-3-fanart-r3z0m-3.webp", "assets/img/portfolio/rasch-crysis-3-fanart-r3z0m-4.webp"], "desc": "Realistic Sci-Fi Character Study: \"Rasch\" (Crysis 3 Fanart)\nDeveloped internally at Brothers Interactive, \"Rasch\" represents our team's proficiency in complex mechanical hard-surface modeling, industrial cybernetic design, and advanced surface weathering. This production-ready asset was built from the ground up to showcase intricate robotic anatomy, layered plating, and realistic metallic wear required for premier current-gen sci-fi, action, and shooter titles.\n\nTechnical Breakdown:\n- Budget: 55K Tris\n- Texturing: PBR workflow, three 2K and one 1K texture sets\n- Target Platforms: PC, PlayStation 5, and Xbox Series X|S\n- Pipeline: Fully optimized with clean mechanical topology and precise articulation pivots, ready for seamless integration into advanced rigging, robotic animation networks, and current-gen gameplay engines.", "tags": [], "src": "https://brothersinteractive.com/projects/r3z0m", "w": 1000, "h": 1000}
  ]
};
